### ISSUE TITLE
Is pkg-modbus v2.0.0 compatible with toit v1.6.22

### ISSUE THREAD

**Issue by gregger2k** [toitlang/pkg-modbus#12]
When trying to convert my toit v1.6.22 app from pkg-modbus v1.2.0 (debug version) to v2.0.0 I get the following compilation error:
```
[classic_monitor.toit] <pkg:pkg-modbus>/bus.toit:148:19: error: Unresolved type: 'Signal'
[classic_monitor.toit]   signal_/monitor.Signal ::= monitor.Signal
[classic_monitor.toit]                   ^~~~~~
[classic_monitor.toit] <pkg:pkg-modbus>/bus.toit:148:38: error: Unresolved identifier: 'Signal'
[classic_monitor.toit]   signal_/monitor.Signal ::= monitor.Signal
[classic_monitor.toit]                                      ^~~~~~
[classic_monitor.toit] Compilation failed.
```
when testing using jaguar v2.0.0-alpha.12 it compiles and operates correctly to the Modbus simulator.
I have only tested the new 2.0 driver using jaguar so far.

Is there an alpha or beta version of toit available?
I could probably get the master compiled for the esp32 side ( I do micropython quite regularly) but I am not sure about the windows app.

**Comment by floitsch** [comment]
I will change the driver not to use `Signal`.
