### ISSUE TITLE
Modbus RTU?

### ISSUE THREAD

**Issue by gregger2k** [toitlang/pkg-modbus#3]
Is there any chance of getting the RTU protocol added.
I have several projects that are using Modbus RTU because TCP/IP is not available.
I would love to switch from Micropython and C and use all toitlang's  cool features but can't unless RTU is available.

Thanks, Greg

**Comment by floitsch** [comment]
Seems like a reasonable/good feature enhancement.

We are currently busy with other things, so it won't happen in the near future, but I added it to my TODO list.
Feel free to ping from time to time (maybe every 2 weeks), to make sure the item doesn't drop too far in my list.

**Comment by gregger2k** [comment]
Just a friendly ping ;-)

I have successfully converted one of my apps from Micropython to Toit.
It reads a Midnite Classic  solar charge controller via modbus-tcp and publishes the data to MQTT and then to Influx with Telegraf.
I especially like the to update apps and firmware over the cloud so easily, and the crash protection toit provides

I would like to convert the rest of my modbus apps over but they are all RTU and writing  / updating a pkg is way above my pay grade!

Thanks, Greg

**Comment by floitsch** [comment]
Could you maybe suggest an inexpensive sensor/device that we could use to develop the driver?

**Comment by gregger2k** [comment]
Probably the easiest way would be to use a Modbus server simulator:
https://github.com/ClassicDIY/ModbusTool
https://sourceforge.net/projects/modrssim2
https://sourceforge.net/projects/pymodslave
https://www.modbusdriver.com/diagslave.html

The simulator will provide a better look under the hood. I will look for sensor/device. Amazon has some Modbus relays but the documentation is questionable.

**Comment by floitsch** [comment]
Thanks. The simulator is a good idea.
In the meantime I also ordered a few sensors from Banggood. They will take some weeks to arrive, though.

**Comment by gregger2k** [comment]
Great work on supporting Modbus RTU! Works great.

**Comment by floitsch** [comment]
Modbus RTU has landed on master, and a v2.0.0 of the package has been published.
