### ISSUE TITLE
wrong number of returned registers

### ISSUE THREAD

**Issue by gregger2k** [toitlang/pkg-modbus#4]
I have an app that every minute requests a block of 21 Modbus registers, parses the data, requests a block of 3 Modbus registers, parses the data, then builds a json string and publishes it by MQTT.
Randomly and infrequently the 21 register call will return 3, or the 3 register call will return 21. I was getting the wrong registers when the 21 call would return 3 or a subscript out of range error when the 21 register call would return 3.
I tried a 1 second delay between register reads but it did not help. The same logic using micro python always worked correctly.
As a workaround I currently read the registers in a while loop and only continue when the correct number of registers are returned.

I will try to set up a test environment using a Modbus server simulator to try to duplicate the problem with a more simple app.

Are there some async reads or something going on in the Modbus driver or something? I looked at the driver but the code is currently above my level of understanding.

**Comment by gregger2k** [comment]
```
  net := net.open
  socket := net.tcp_connect MODHOST MODPORT
  modclient := modbus.Client.tcp socket --server_address=1
  
  registers := []
  while registers.size != 21:
    registers = modclient.read_holding_registers 4114 21
    print "Req: 21 Return: $registers.size $registers"
  BatV := registers[0] / 10.0
  PvV := registers[1] / 10.0
  BatA := registers[2] / 10.0
  KWH := registers[3] / 10.0
  Power := registers[4]
  Mode := registers[5] >> 8
  PvA := registers[6] /10.0
  BatT := registers[17] * 0.18 + 32
  FetT := registers[18] * 0.18 + 32   
  PcbT := registers[19] * 0.18 + 32

  wregisters := []
  while wregisters.size != 3:
    wregisters = modclient.read_holding_registers 4370 3
    print"Req: 3 Return: $wregisters.size $wregisters"
  WizAt := wregisters[0]
  WizA := 0
  if WizAt >= 32768 :
    WizA = (WizAt - 65536) / 10.0
  else:
    WizA = WizAt / 10.0
  SOC := wregisters[2]
  //AH := registers[6]
  modclient.close

  payload := json.encode {
    "BatV":BatV, "PvV":PvV, "BatA":BatA, "KWH":KWH, "Power":Power, "Mode":Mode, "PvA":PvA,
    "BatT":BatT, "FetT":FetT, "PcbT":PcbT, "WizA":WizA, "SOC":SOC
  }
  topic := "classic/data/"
  
  if (wregisters.size == 3) and (registers.size == 21):
    client.publish topic payload
  else:
    print "modbus return error!"
  
  client.close
  print "data  `$payload.to_string_non_throwing"```
```

**Comment by gregger2k** [comment]
Here is an example of the wrong numbers of registers being returned:
```
data "BatV":51.00,"PvV":0.00,"BatA":0.00,"KWH":3.80,"Power":0,"Mode":0,"PvA":0.00,"BatT":75.56,"FetT":80.78,"PcbT":95.90,"WizA":-1.80,"SOC":98}
Req: 3 Return: 3 [65518, 13897, 98]
Req: 3 Return: 21 [510, 0, 0, 38, 0, 0, 0, 0, 1441, 0, 71, 48615, 65513, 57871, 4, 12548, 61952, 242, 272, 355, 179]
Req: 21 Return: 21 [510, 0, 0, 38, 0, 0, 0, 0, 1441, 0, 71, 48615, 65513, 57871, 4, 12292, 61952, 242, 271, 355, 179]
```

**Comment by gregger2k** [comment]
And the 21 register request returning 3:
```
data  {"BatV":50.90,"PvV":0.00,"BatA":0.00,"KWH":3.80,"Power":0,"Mode":0,"PvA":0.00,"BatT":75.02,"FetT":79.70,"PcbT":94.64,"WizA":-1.90,"SOC":98}
Req: 3 Return: 3 [65517, 62024, 98]
Req: 21 Return: 21 [509, 0, 0, 38, 0, 0, 0, 0, 1441, 0, 71, 48615, 65513, 57871, 4, 12548, 61952, 239, 265, 348, 207]
Req: 21 Return: 3 [65517, 9288, 98]
```

**Comment by floitsch** [comment]
That's indeed strange.
Incidentally, I have been working on the modbus package during the last two days.

At the moment I don't really see how this could happen: Modbus TCP uses transaction IDs for the request and when receiving the response. As such, there shouldn't be any way to mix up the requests.
Furthermore, your requests are completely serialized: there is no concurrency that could confuse the sensor.

I will upload a debug version of the modbus package that keeps track of the last bytes that have been sent and received on the socket. That should confirm whether our transaction IDs are correct.

I also noticed that we sometimes send the header and the data of a modbus-frame in two writes to the socket. Maybe the other side doesn't like that. (I had at least one modbus emulator that complained). Modbus TCP is not supposed to care about fragmentation, but maybe the sensor doesn't do it right. I will also upload a version where it always sends the frame in one TCP packet (hopefully).

A different question: you are setting the server address to 1. Does that mean that you are using a Modbus TCP -> Modbus RTU gateway? I don't think this is related to this issue, so this is just for my curiosity.

**Comment by floitsch** [comment]
I have uploaded a branch with debugging support.

If you are up for it, here are some instructions on how to use it. If you encounter issues, reply here, or try to reach me/us on Discord: https://discord.gg/Q7Y9VQ5nh2

- clone the debug branch (can be into your project directory):
  ```
  git clone -b floitsch/debug_issue4 https://github.com/toitlang/pkg-modbus.git
  ```
- uninstall the old modbus package: `toit pkg uninstall modbus`
- install the downloaded debug version: `toit pkg install --local --name=modbus ./pkg-modbus`
  If you cloned the debug modbus into a different directory, just adjust the `./pkg_modbus`.
- Change your program as follows:

```
  // Add a new import:
  import modbus.tcp as modbus

  ...

  net := net.open
  socket := net.tcp_connect MODHOST MODPORT
  // New line:
  transport := modbus.DebugTcpTransport socket
  // Change the constructor call: no ".tcp" and instead of the socket use the transport:
  modclient := modbus.Client transport --server_address=1
```

Then, when things go wrong, call `transport.print_debug`.
For example in your code:
```
  while registers.size != 21:
    registers = modclient.read_holding_registers 4114 21
    print "Req: 21 Return: $registers.size $registers"
    transport.print_debug
```

I added an example using the debug transport:
https://github.com/toitlang/pkg-modbus/blob/1b34eb4a3c1587603612c718e5e51ae1c4d5861e/examples/holding_registers_debug.toit



### To go back:
- uninstall the debug package: `toit pkg uninstall modbus`
- install the original package: `toit pkg install toitlang/pkg-modbus@1`
- remove the downloaded folder: `rm -r pkg-modbus`

**Comment by gregger2k** [comment]
I am nut using a gateway, connecting directly to a Midnite Solar Classic charge controller. It could be a bug in the Classic but the MicroPython version did not have the problem. 
I will install the debug version later today.
Thanks Greg

**Comment by gregger2k** [comment]
I tried your changes:
```
  net := net.open
  socket := net.tcp_connect MODHOST MODPORT
  transport := modbus.DebugTcpTransport socket
  modclient := modbus.Client transport --server_address=1
  
  registers := []
  while registers.size != 21:
    registers = modclient.read_holding_registers 4114 21
    print "Req: 21 Return: $registers.size $registers"
    transport.print_debug
  BatV := registers[0] / 10.0
  PvV := registers[1] / 10.0
```
...

But when I try to run I get:
```[classic_mon.toit] 2022-07-13T15:19:31.666331Z: <process initiated>
[classic_mon.toit] [modbus] DEBUG: read_holding_registers count=21, address=4114
[classic_mon.toit] 2022-07-13T15:19:31.982682Z: <stack trace>
[classic_mon.toit] Argument mismatch for 'DebugWriter_.write'.
[classic_mon.toit]   0: Writer.write              <sdk>/writer.toit:37:23
[classic_mon.toit]   1: TcpFramer.write           <pkg:pkg-modbus>/tcp.toit:52:12
[classic_mon.toit]   2: DebugTcpTransport.write   <pkg:pkg-modbus>/tcp.toit:98:12
[classic_mon.toit]   3: Client.read_holding_registers.<block> <pkg:pkg-modbus>/client.toit:97:18
[classic_mon.toit]   4: Client.read_holding_registers <pkg:pkg-modbus>/client.toit:88:3
[classic_mon.toit]   5: main                      /c:/Cloud/toit/modtest/classic_mon.toit:39:27
[classic_mon.toit]   6: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
[classic_mon.toit] 
[classic_mon.toit] 
[classic_mon.toit] 
[classic_mon.toit] 2022-07-13T15:19:32.046255Z: <process terminated - exit code: 1>
```
Sorry for my ignorance .  I will try the example debug code with a simulator and see if I get further.

**Comment by floitsch** [comment]
Ah. That's probably a bug on my side.
Let me upload a new version.

**Comment by floitsch** [comment]
My code was tested with a newer Toit which changed the way the `Writer` works.
I have uploaded a new version that should work with the toit.io executable.
(That said, I didn't test it).

**Comment by gregger2k** [comment]
Your update  seems to work but I do not see any additional debug information being printed.  I had previously commented out the Client read informational debug print lines to reduce noise in the logs. I have re-enabled the debug info messages. The client debug print statements always requested the proper number of registers.
I can test with a newer version of toit if necessary.
```
[classic_mon.toit] 2022-07-13T15:43:53.587423Z: <process initiated>
[classic_mon.toit] [modbus] DEBUG: read_holding_registers address=4114, count=21
[classic_mon.toit] Req: 21 Return: 21 [549, 782, 134, 7, 739, 1284, 98, 866, 1441, 0, 14, 48653, 65513, 57942, 4, 12292, 45568, 198, 368, 404, 0]
[classic_mon.toit] [modbus] DEBUG: read_holding_registers address=4370, count=3
[classic_mon.toit] Req: 3 Return: 21 [549, 783, 134, 7, 741, 1283, 98, 866, 1441, 0, 14, 48653, 65513, 57942, 4, 12292, 45568, 199, 368, 405, 0]
[classic_mon.toit] [modbus] DEBUG: read_holding_registers count=3, address=4370
[classic_mon.toit] Req: 3 Return: 3 [99, 46148, 97]
[classic_mon.toit] data  {"BatV":54.90,"PvV":78.20,"BatA":13.40,"KWH":0.70,"Power":739,"Mode":5,"PvA":9.80,"BatT":67.64,"FetT":98.24,"PcbT":104.72,"WizA":9.90,"SOC":97}
[classic_mon.toit] 2022-07-13T15:43:54.311646Z: <process terminated - exit code: 0>
```

**Comment by floitsch** [comment]
The crucial line is this one:
```
transport.print_debug
```
You can call it anytime you want. It should print the last 16 messages that were sent or received.

**Comment by gregger2k** [comment]
the  transport.print_debug did not seem to work in the while loop so I simplified my code to do the transport debug if there is an error. Now I will need to let it run until the error occurs. Sometimes it takes a while.
How can I change the level of debug logging without editing the client code?
```
  registers = modclient.read_holding_registers 4114 21
  print "Req: 21 Return: $registers.size $registers"
  if registers.size != 21:
    transport.print_debug
```

**Comment by floitsch** [comment]
Unless I made a mistake there shouldn't be additional logging, except when you call `print_debug`.

**Comment by gregger2k** [comment]
From pkg-modbus 1.1.0 > src > client.toit

```
  read_holding_registers address/int count/int -> List:
    logger_.debug "read_holding_registers" --tags={"address": address, "count": count}
    identifier := next_identifier_++
    request := ReadHoldingRegistersRequest
      --address=address
      --count=count
```

the logger_.debug statement is what I did have commented out. I have un commented the debug lines. The number of register requested was always correct.

!!! just got the error, request 21 returned 3. out of bounds because of the wrong number of registers returned.
```
EXCEPTION error. 
OUT_OF_BOUNDS
  0: List_.[]                  <sdk>/core/collections.toit:1755:24
  1: main                      /C:/Cloud/toit/modtest/classic_mon.toit:45:19
  2: __entry__.<lambda>        <sdk>/core/entry.toit:48:20


25s ago
stack trace
  #[]
25s ago
message
<- -- 3622951429
25s ago
message
  #[00, 00, 00, 00, 00, 09, 01, 03, 06, 00, 22, 47, 4a, 00, 63, ]
25s ago
message
<- -- 3622943719
25s ago
message
  #[10, 12, 00, 15, ]
25s ago
message
-> -- 3622935748
25s ago
message
  #[00, 00, 00, 00, 00, 06, 01, 03, ]
25s ago
message
-> -- 3622926376
25s ago
message
Req: 21 Return: 3 [34, 18250, 99]
25s ago
message
[modbus] DEBUG: read_holding_registers address=4114, count=21
```

**Comment by floitsch** [comment]
Hmm. The output is hard to read, and it looks like at least one line is missing: every `->` should be followed by the data.

I uploaded a new version that should print all the debug output in one nice block. Could you maybe try that one. (Should be a simple `git pull` in the `toit-pkg` directory).

In the meantime I will try to make sense of the output that is pasted here.

**Comment by gregger2k** [comment]
I will pull in the new version. Here is a sanitized copy op the 3 call returning 20 in the mean time. I guess I need to learn how to use discord!
```
process stop
modbus return error!
  #[]
<- -- 4228704201
  #[00, 01, 00, 00, 00, 2d, 01, 03, 2a, 02, 23, 03, 40, 00, 2e, 00, 15, 00, fc, 05, 03, 00, 22, 03, 62, 05, a1, 00, 00, 00, 27, be, 0d, ff, e9, e2, 56, 00, 04, 30, 04, b2, 00, 00, dc, 01, d9, 01, fe, 00, 00, ]
<- -- 4228696343
  #[11, 12, 00, 03, ]
-> -- 4228686470
  #[00, 01, 00, 00, 00, 06, 01, 03, ]
-> -- 4228679531
  #[]
<- -- 4228638633
  #[00, 00, 00, 00, 00, 2d, 01, 03, 2a, 02, 23, 03, 40, 00, 2f, 00, 15, 01, 02, 05, 04, 00, 23, 03, 62, 05, a1, 00, 00, 00, 27, be, 0d, ff, e9, e2, 56, 00, 04, 30, 04, b2, 00, 00, dc, 01, d9, 01, fe, 00, 00, ]
<- -- 4228631860
  #[10, 12, 00, 15, ]
-> -- 4228606543
  #[00, 00, 00, 00, 00, 06, 01, 03, ]
-> -- 4228580935
Req: 3 Return: 21 [547, 832, 46, 21, 252, 1283, 34, 866, 1441, 0, 39, 48653, 65513, 57942, 4, 12292, 45568, 220, 473, 510, 0]
[modbus] DEBUG: read_holding_registers count=3, address=4370
Req: 21 Return: 21 [547, 832, 47, 21, 258, 1284, 35, 866, 1441, 0, 39, 48653, 65513, 57942, 4, 12292, 45568, 220, 473, 510, 0]
[modbus] DEBUG: read_holding_registers address=4114, count=21
```
and a clean version of the other. Much less data returned.
```
EXCEPTION error. 
OUT_OF_BOUNDS
  0: List_.[]                  <sdk>/core/collections.toit:1755:24
  1: main                      /C:/Cloud/toit/modtest/classic_mon.toit:45:19
  2: __entry__.<lambda>        <sdk>/core/entry.toit:48:20

stack trace
  #[]
<- -- 3622951429
  #[00, 00, 00, 00, 00, 09, 01, 03, 06, 00, 22, 47, 4a, 00, 63, ]
<- -- 3622943719
  #[10, 12, 00, 15, ]
-> -- 3622935748
  #[00, 00, 00, 00, 00, 06, 01, 03, ]
-> -- 3622926376
Req: 21 Return: 3 [34, 18250, 99]
[modbus] DEBUG: read_holding_registers address=4114, count=21
```

**Comment by floitsch** [comment]
I had to add a fix to what I uploaded...
Please git-pull again.

For chat, you can also just go on toit.io (or console.toit.io) and use the chat there. That might be the easiest.

**Comment by floitsch** [comment]
Looked into the debug information you gave me.

In correct order and with some comments.
```
-> -- 4228580935
 // vvvvvv  First message to the device. transaction ID is 0..
  #[00, 00, 00, 00, 00, 06, 01, 03, ]
//                              ^^^  We are trying to read holding registers.
-> -- 4228606543
// The second part of the message says which register (0x10, 0x12), and how many: 0x15.
  #[10, 12, 00, 15, ]
<- -- 4228631860
// We correctly receive the registers.
  #[00, 00, 00, 00, 00, 2d, 01, 03, 2a, 02, 23, 03, 40, 00, 2f, 00, 15, 01, 02, 05, 04, 00, 23, 03, 62, 05, a1, 00, 00, 00, 27, be, 0d, ff, e9, e2, 56, 00, 04, 30, 04, b2, 00, 00, dc, 01, d9, 01, fe, 00, 00, ]
<- -- 4228638633
// Just a signal that nothing more was to read.
  #[]
-> -- 4228679531
// We are trying again.
// Now the transaction ID is 1. The rest is the same.
  #[00, 01, 00, 00, 00, 06, 01, 03, ]
-> -- 4228686470
// The register has changed, but we also only ask for 3 values.
  #[11, 12, 00, 03, ]
<- -- 4228696343
// The response uses the correct transaction ID, but gives us way too many values.
// Also looks like it's using the register-address of the previous call.
  #[00, 01, 00, 00, 00, 2d, 01, 03, 2a, 02, 23, 03, 40, 00, 2e, 00, 15, 00, fc, 05, 03, 00, 22, 03, 62, 05, a1, 00, 00, 00, 27, be, 0d, ff, e9, e2, 56, 00, 04, 30, 04, b2, 00, 00, dc, 01, d9, 01, fe, 00, 00, ]
```

So far I'm not really sure what the reason could be.
I can try to send our packets in one TCP packet, but the server should be able to deal with that.

**Comment by gregger2k** [comment]
pulled and deployed. I will let it cook and see how it goes.
At least the problem is not fatal, I can program around it.
Now if we only had the serial RTU driver available I could convert more apps.

Thanks for all your help...
Greg

**Comment by floitsch** [comment]
I'm working on the RTU driver right now.
Should have something working by tomorrow. Then a bit of review..., but it should be out next week :)

**Comment by gregger2k** [comment]
**So far so good with your latest update!!!  The app has been running over 11.5 hours with 690 executions with 0 errors!!!!**
I did have one failure with the reformatted debug code but it was before the latest pull.

I will provide updated results tomorrow AM

When you update the production driver you might consider removing the 2 debug calls  in:
**pkg-modbus 1.1.0/src/client.toit**
```
  read_holding_registers address/int count/int -> List:
    logger_.debug "read_holding_registers" --tags={"address": address, "count": count}

  write_holding_registers address/int registers/List --preset_count/int=0:
    logger_.debug "write_holding_registers" --tags={"address": address, "registers": registers}

```
I look forward to testing the RTU driver. I have more applications using RTU than TCP.
Thanks...

**Comment by floitsch** [comment]
Good to hear.
You can change the logging output by passing in a logger to the modbus client:
```
modclient := modbus.Client.tcp socket
    --server_address=1
    --logger=((log.default.with_name "modbus").with_level log.FATAL_LEVEL)
```
See here: https://libs.toit.io/log/library-summary

**Comment by gregger2k** [comment]
Thanks for the information on logging.
Over 23 hours of 60 second intervals and 0 errors! Looks kike the 1 TCP packet resolved the modbus errors with the Midnite Classic charge controller.

Since you are deep in the Modbus driver is there any chance of getting the read coils and write coils functions on the roadmap?
When accessing and controlling PLC's and VFD's the coil functions are sometimes necessary for accessing switches and flags. Even the single coil read/write function would be sufficient.

Thanks again for resolving the wrong number of registers returned problem.

**Comment by floitsch** [comment]
Great!
Coil functions are already written and will be in the next release.

**Comment by floitsch** [comment]
A new version that sends data in one packet has been released. (Not new functionality in that release).
You should be able to go back to the released package instead of using a git-checkout.
